export { default as Navbar } from './Navbar/Navbar'
export { default as Info } from './Info/Info'
export { default as Post } from './Post/Post'
export { default as Event } from './Event/Event'
export { default as Alumnus } from './Alumnus/Alumnus'
export { default as Partners } from './Partners/Partners'
export { default as Footer } from './Footer/Footer'
